

export const AppString = {
    AppName: "Jumunona",
    want_to: 'Хочу',
    subscription: 'Подписки',
    story: 'История',
    wallet: 'Кошелёк',
    my_order: 'Мои заказы',
    not_paid: 'Неоплачен',
    treatment: 'Обработка',
    sent: 'Отправлен',
    review: 'Отзыв',
    return: 'Возврат',
    pay: 'Оплатить',
    address: 'Адрес',
    body: 'Тело',
    team: 'Команда',
    reviews: 'Отзывы',
    help: 'Помощь',
    write: 'Написать',
    status_of_order: '#Status of the order',
    left: 'осталось',
    my_addresses: 'Мои адреса',
    notifications: 'Уведомления',
    city: 'Город',
    feedback_and_help: 'Обратная связь и помощь',
    trem_and_privacy: 'Условия и конфиденциальность',
    about_us: 'О нас',
    clear_catch: 'Очистить кэш',
    catch_for_update: 'Проверьте наличие обновлений',
    go_out: "Выйти",
    name: "Имя",
    gender: "Пол",
    age: "Возраст",
    number: "Номер",
    mail: "Почта",
    change_password: "Изменить пароль",
    delete_account: "Удалить аккаунт",
    phone_number: 'Номер телефона',
    current_phone_number: 'Текущий номер телефона',
    change: 'Изменить',
    back: 'Назад',
    please_select_a_reason: "Пожалуйста, выберите причину",
    need_to_turn_off_your_phone: "Нужно отключить телефон",
    need_to_turn_off_email: "Нужно отключить почту",
    security_privacy: "Безопасность/Конфиденциальность",
    addition_account: "Дополнительный аккаунт",
    difficulty_with_shopping: "Трудности с покупками",
    other: "Другой",
    please_provide_a_reason: "Пожалуйста, укажите причину",
    next_step: "Следующий шаг",
    deleting_an_account: "Удаление аккаунта",
    by_deleting_you_waive_rights_Title: "При удалении вы отказываетесь от следующих прав:",
    by_deleting_you_waive_rights_Desc: "1. Все записи о транзакциях будут окончательно удалены. Пожалуйста, удостоверьтесь, что все транзакции завершены и не вызывают споров. При закрытии учетной записи автоматически утрачиваются любые права и преимущества, связанные с возвратами, возвратами средств и разрешением споров, возникшими из истории транзакций. \n2. Ваши данные для идентификации, сведения об учетной записи и льготы членства, такие как J coin, будут окончательно удалены и не могут быть восстановлены.",
    the_following_conditions_must_be_met_Title: "Должны быть выполнены следующие условия:",
    the_following_conditions_must_be_met_Desc: "1. На аккаунте не было недавних транзакций. В аккаунте отсутствуют невыполненные заказы, а также завершенные заказы, сделанные менее 15 дней назад. \n2. На аккаунте нет возвратов. Ваш аккаунт не имеет неразрешенных споров или жалоб. \n3. Аккаунт не нарушал правила. На аккаунте отсутствует история нарушений правил или ограничений.",
    i_have_read_and_agree_to_the_cancellation_terms: "Я прочитал(а) и согласен(а) с условиями отмены.",
    confirm_delete: "Подтвердить удаление",
    current_mail: 'Текущая почта',
    verify_phone_no: "Подтвердите номер телефона",
    confirmation_code: "Код подтверждения",
    enter_sms_code: "Введите SMS-код",
    enter_phone: "Введите телефона",
    cancel: "Отменить",
    confirm: "Подтвердить",
    get_code: "Получить код",
    failed_to_delete_acc: "Не удалось удалить аккаунт.",
    failed_acc_delete_reason: "На вашем аккаунте были транзакции в течение последних 15 дней. Пожалуйста, завершите транзакции, подтвердите получение товара или повторите попытку через 15 дней после завершения транзакций.",
    change_phone_number: "Изменить номер телефона",
    enter_new_number: "Введите новый номер",
    enter_your_new_nubmer: "Введите ваш новый номер телефона",
    enter_new_email: "Введите новую почту",
    enter_your_new_email: "Введите вашу новую почту",
    change_email: "Изменить почту",
    new_password: "Новый пароль",
    create_new_password: "Придумайте новый пароль",
    confrim_new_password: "Подтвердите пароль",
    enter_your_pass_again: "Введите пароль ещё раз",
    sucessfully_changed: 'Успешно изменено',
    go_back_to_the_main_page: 'Вернуться на главную(05)',
    review_example: "Впечатление: Вполне соответствует ожиданиям \nКачество: Подошва достаточно мягкая \nОпыт: Подошва с антискользящим покрытием \nВ целом, вполне удовлетворительно.",
    my_reviews: "Мои отзывы",
    reviews_for_last_180_days: "Отзывы за последние 180 дней",
    notification_Settings: "Настройки уведомлений",
    receive_notification: "Получение уведомлений",
    receive_msg_notification: "Получать уведомления о сообщениях",
    including_responses_from_support_and_chat: "Включая ответы от службы поддержки и чата",
    Receive_notifications_from_the_platform: "Получать уведомления от платформы",
    Including_logistics_updates_promotional_offers_interactive_messages_etc: "Включая обновления логистики, рекламные предложения, интерактивные сообщения и т. д.",
    city_name: 'Название города',
    tajakistan: 'Таджикистан',
    term_of_use: "Условия использования",
    privacy_policy: "Политика конфиденциальности",
    personal_info: "Персональные данные",
    conditions: 'Условия',
    trem_of_use: 'Условия использования',
    system_permissions: 'Системные полномочия',
    pertional_information: 'Персональные данные',
    camera_and_alblum: 'Камера & Альбом',
    take_photo_select_photo_upload_photo: 'Фотографируйте, выбирайте и загружайте фотографии и т. д.',
    location: 'Локация',
    using_your_locations_currect_curriencies_and_privacies_will_beProvided: 'Используя ваше местоположение, будут предоставлены корректные валюты и цены',
    photo_and_contacts: "Телефон & контакты",
    implement_function_telephone: 'Реализация функций, таких как консультации по телефону, быстрое заполнение адреса и т. д.',
    estimate: "Оценить",
    license_agreement: "Лицензионное соглашение",
    copyright: "Авторские права",
    copyringt_information: "Информация об авторских правах",
    product_name: 'Название товара',
    add_to_cart: 'В корзину',
    buy: 'Купить'

}