import { AppString } from './AppStrings';

export const RouteNames = {
  home: 'Home',
  shophome: 'ShopHome',
  shopcategoriesHome: 'shopCategories',

  categoriesHome: 'Categories',
  messgaesScreen: 'Messages',
  cartScreen: 'Cart',
  profileScreen: 'Profile',
  welcome: 'Welcome',
  login: 'Login',
  signup: 'Signup',
  main: 'Main',
  forgotPassword: 'ForgotPassword',
  setting: 'Настройки',
  profileDetail: 'Профиль',
  viewPhoneNumber: AppString.phone_number,

  deleteAccount: 'Удаление аккаунта',
  confirmDeleteAccount: 'Confirm Delete Account',
  changePhone: 'ChangePhone',
  changeEmail: 'ChangeEmail',
  changePassword: 'ChangePassword',
  sucessfulChangePassword: 'Sucessful Change Password',
  myReviews: 'My Reviews',
  notificationSetting: 'Notification Settings',
  selectCity: 'Select City',
  term_of_use: 'Term Of Use',
  privacy_policy: 'Privacy Policy',
  personal_info: 'Personal Information',
  conditions: AppString.conditions,
  system_permission: AppString.system_permissions,
  aboutUs: 'About Us',
  copyright: 'Copyright',
  licenseAgreement: 'License Agreement',
  favorite: AppString.want_to,
  product_detail: 'Product Detail',
  product_review_screen: 'ProudctReviewsScreen',
  select_product_color_size: 'Select product color size',
  chat_screen: 'Chat',
  chatScreenUsersList: 'Chat Screen User List',
  shopchatScreenUsersList: 'shop Chat Screen User List',

  product_search_screen: 'product_search_screen',
  categories: "Categories Screen",
  chatSetting: AppString.chatSettings,
  shopSettings: 'Shop Settings',
  myAddress: AppString.my_addresses,
  addAndEditpassword: AppString.changeAddress,

  cartConfirmOrder: "Cart Confirm Order Screen",
  shopHomeScreen: 'ShopHomeScreen',
  myOrder: 'My Order',
  orderDetails: 'Order Details',
  refund_details: AppString.refund_details,
  logistic_screen: AppString.logistics,
  review: AppString.review,

  changeAddress: "Change Address",
  select_return_region: AppString.select_your_region,
  refund: AppString.refund,
  return_exchange: AppString.return_exchange,
  exchangeDetail: "Exchange Detail Screen",
  subscribers_screen: "subscribers_screen",
  walletScreen: AppString.wallet,
  historyScreen: AppString.story
};
